# Utiliser l'image VLC officielle
FROM videolan/vlc:latest

# Définir des variables d'environnement
ENV DEBIAN_FRONTEND=noninteractive

# Mettre à jour et installer les paquets nécessaires
RUN apt-get update && \
    apt-get install -y \
    vlc \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Ajouter un utilisateur pour VLC
RUN useradd -m -s /bin/bash vlcuser

# Copier le script de démarrage dans le conteneur
COPY start.sh /home/vlcuser/start.sh

# Définir les permissions appropriées pour le script
RUN chmod +x /home/vlcuser/start.sh

# Exposer le port de streaming HTTP
EXPOSE 8080

# Définir l'utilisateur et la commande pour exécuter le script
USER vlcuser
CMD ["/home/vlcuser/start.sh"]
